import { useEffect, useRef, useState } from 'react';
import { ShoppingBag, Heart, Search, Menu, X, MapPin, UserRound, SlidersHorizontal, Plus, Minus, Check, Droplets, Sun, FlaskConical, ChevronDown, ChevronRight, Camera as Instagram } from 'lucide-react';
import SmoothTab from './components/smooth-tab';
import BrandLogo from './components/brand-logo';
import SiteFooter from './components/site-footer';
import { MaisonHero, MaisonEditorial } from './components/maison';
import Promotions from './components/promotions';
import Profile from './components/profile';
import { MobileHeader, MobileHome, MobileDock } from './components/mobile-ui';
import { readUIMode, isMobileUI, modeURL } from './ui-mode';
import { concepts, products, categories, filterProducts, basketTotal, money, initialView, initialConcept as readInitialConcept } from './catalog';

const liveSite = 'https://koko-beauty-kz.d-authang465.chatgpt.site/';
function initialConcept() { return readInitialConcept(location.search); }
function saved(name, fallback) { try { return JSON.parse(localStorage.getItem(name)) ?? fallback; } catch { return fallback; } }
function initialCart() {
  const raw = saved('koko-design-cart', {});
  return Object.fromEntries(products.filter(p => Number.isInteger(raw?.[p.id]) && raw[p.id] > 0 && raw[p.id] <= 20).map(p => [p.id, raw[p.id]]));
}
function IconButton({ label, children, ...props }) { return <button className="icon-button" type="button" aria-label={label} title={label} {...props}>{children}</button>; }
function ProductImage({ product, className = '', ...props }) { return <img className={`product-image ${className}`} src={product.image} alt={`${product.brand} ${product.name}, ${product.volume}`} loading="lazy" {...props} />; }

function ElectricHero({ browse, open }) {
  return <section className="electric-hero" aria-label="Косметика KOKO">
    <div className="electric-main-copy"><h1>Твоя<br />косметика.<br /><span>Твои правила.</span></h1><p>Корейский уход, любимые бренды<br className="desktop-break" /> и новые поводы полюбить себя.</p><button className="primary-button" onClick={() => browse()}>Найти своё</button><div className="electric-copy-bottom"><span>Собери свою beauty-рутину</span><span>KOKO / BEAUTY STORE</span></div></div>
    <div className="electric-portrait"><img src="./images/beauty-editorial.png" alt="Beauty-портрет с естественным сиянием кожи" fetchPriority="high" /><span className="portrait-word">GO<br />BEAUTY.</span><span className="electric-sticker">УХОД<br />С ХАРАКТЕРОМ</span></div>
    <button className="electric-product" onClick={() => open(products[0])}><span>Вечер начинается с очищения</span><ProductImage product={products[0]} /><div><b>Clean It Zero</b><span>BANILA CO</span><ChevronRight aria-hidden="true" /></div></button>
    <button className="electric-spf" onClick={() => browse('spf')}><Sun size={34} aria-hidden="true" /><span>SPF —<br />каждый день</span><small>Открыть подборку</small></button>
  </section>;
}
function GlossHero({ browse, open }) {
  return <section className="gloss-hero" aria-label="Коллекция косметики KOKO">
    <div className="gloss-copy"><h1>Красота<br />как чувство.</h1><p>Текстуры, к которым хочется<br />прикасаться. Уход, которому<br />хочется уделить время.</p><button className="primary-button" onClick={() => browse()}>Открыть коллекцию</button><div className="gloss-note"><span className="gloss-flower" aria-hidden="true">K</span><span>Маленький ритуал.<br />Большое удовольствие.</span></div></div>
    <div className="gloss-portrait"><img src="./images/beauty-editorial.png" alt="Редакционный beauty-портрет" fetchPriority="high" /><span className="gloss-signature">the beauty<br /><i>of you</i></span></div>
    <button className="gloss-still" onClick={() => open(products[0])}><img src="./images/gloss.jpg" alt="Розовый косметический флакон с каплями воды" fetchPriority="high" /><div><span>В фокусе KOKO</span><h2>Мягкость —<br />новая сила</h2><span className="underlined">Начать с очищения</span></div></button>
  </section>;
}
function SkinHero({ browse, open }) {
  return <section className="skin-hero" aria-label="Уход за кожей KOKO">
    <div className="skin-copy"><h1>Хороший уход.<br /><span>Ничего лишнего.</span></h1><p>Понятные составы, комфортные текстуры<br className="desktop-break" /> и базовые шаги для вашей кожи.</p><button className="primary-button" onClick={() => browse()}>Собрать уход</button><div className="skin-routine-nav"><button onClick={() => browse('cleansing')}><Droplets aria-hidden="true" />Очищение</button><button onClick={() => browse('cream')}><FlaskConical aria-hidden="true" />Увлажнение</button><button onClick={() => browse('spf')}><Sun aria-hidden="true" />Защита</button></div></div>
    <div className="skin-art"><img src="./images/skin.jpg" alt="Флаконы средств для ухода на водной поверхности" fetchPriority="high" /><div className="skin-image-caption"><span>Утро. Вода. Твой уход.</span><span>KEEP IT SIMPLE</span></div></div>
    <button className="skin-featured" onClick={() => open(products[1])}><ProductImage product={products[1]} /><div><span>Один шаг к своей рутине</span><b>ANUA Heartleaf 77%</b><small>Тонер · 250 мл</small></div><Plus aria-hidden="true" /></button>
  </section>;
}
function ProductCard({ product, favorite, quantity, toggleFavorite, add, open }) {
  return <article className="product-card">
    <div className="product-stage" style={{ '--product-tint': product.color }}><button className="product-picture-button" onClick={() => open(product)} aria-label={`Подробнее: ${product.brand} ${product.name}`}><ProductImage product={product} /></button><IconButton label={`${favorite ? 'Удалить из' : 'Добавить в'} избранное: ${product.name}`} className={`favorite-button ${favorite ? 'is-favorite' : ''}`} aria-pressed={favorite} onClick={() => toggleFavorite(product.id)}><Heart size={20} fill={favorite ? 'currentColor' : 'none'} aria-hidden="true" /></IconButton><span className="ingredient-label">{product.ingredient}</span></div>
    <div className="product-info"><span className="product-brand">{product.brand}</span><button className="product-name" onClick={() => open(product)}>{product.name}</button><p>{product.type} · {product.volume}</p><div className="product-buy"><b>{money(product.price)}</b><button className={`add-button ${quantity ? 'is-added' : ''}`} onClick={() => add(product.id)} disabled={quantity >= 20} aria-label={`Добавить в корзину: ${product.name}`}>{quantity ? <Check size={17} aria-hidden="true" /> : <Plus size={17} aria-hidden="true" />}<span>{quantity ? `В корзине · ${quantity}` : 'В корзину'}</span></button></div></div>
  </article>;
}
function EditorialSections({ concept, browse, open }) {
  if (concept === 'maison') return <MaisonEditorial browse={browse} />;
  if (concept === 'electric') return <>
    <section className="electric-brand-rail" aria-label="Бренды KOKO"><span>BEAUTY, YOUR WAY.</span><b>ANUA</b><b>cosrx</b><b>abib</b><b>BANILA CO</b><b>ROUND LAB</b></section>
    <section className="electric-edit section-wrap"><div><h2>Три шага.<br />Твой новый ритуал.</h2><p>Очищение, увлажнение, защита.<br />Начни с простого.</p><button className="primary-button" onClick={() => browse()}>Собрать косметичку</button></div><button className="routine-product routine-pink" onClick={() => open(products[0])}><span>ОЧИЩАЙ</span><ProductImage product={products[0]} /><b>BANILA CO</b></button><button className="routine-product routine-blue" onClick={() => open(products[2])}><span>УВЛАЖНЯЙ</span><ProductImage product={products[2]} /><b>COSRX</b></button><button className="routine-product routine-lime" onClick={() => open(products[3])}><span>ЗАЩИЩАЙ</span><ProductImage product={products[3]} /><b>BEAUTY OF JOSEON</b></button></section>
  </>;
  if (concept === 'gloss') return <section className="gloss-editorial"><div className="gloss-editorial-photo"><img src="./images/gloss.jpg" alt="Розовая косметика с каплями на флаконе" loading="lazy" /></div><div className="gloss-editorial-copy"><h2>Время<br /><i>для себя.</i></h2><p>Пара минут у зеркала. Любимая текстура. Привычное движение. Красота начинается с внимания к себе.</p><button className="primary-button" onClick={() => browse('cleansing')}>Мой вечерний ритуал</button></div><div className="gloss-editorial-product"><span>На полке редакции</span><ProductImage product={products[0]} /><h3>Мягкое начало<br />вечера</h3><button className="text-button" onClick={() => open(products[0])}>Открыть BANILA CO</button></div></section>;
  return <section id="ingredient-archive" className="skin-archive section-wrap"><div className="skin-archive-title"><h2>Состав имеет<br />значение.</h2><p>Выберите свой следующий шаг.</p></div><div className="skin-archive-list">{[['Хауттюйния', 'Тонер для ежедневного ухода', 'toner'], ['Муцин', 'Увлажняющая эссенция', 'serum'], ['Берёзовый сок', 'Комфортная кремовая текстура', 'cream']].map(([name, note, category]) => <button key={name} onClick={() => browse(category)}><div><h3>{name}</h3><p>{note}</p></div><span>Смотреть<ChevronRight size={18} aria-hidden="true" /></span></button>)}</div></section>;
}

export default function App() {
  const [uiMode, setUIMode] = useState(() => readUIMode(location.search));
  const [narrow, setNarrow] = useState(() => typeof window !== 'undefined' && window.matchMedia('(max-width: 700px)').matches);
  const mobileUI = isMobileUI(uiMode, narrow);
  useEffect(() => { const media = window.matchMedia('(max-width: 700px)'); const resize = () => setNarrow(media.matches); const back = () => setUIMode(readUIMode(location.search)); media.addEventListener('change', resize); addEventListener('popstate', back); return () => { media.removeEventListener('change', resize); removeEventListener('popstate', back); }; }, []);
  function switchUI(mode) { setUIMode(mode); history.pushState(null, '', modeURL(location.href, mode)); }
  const [concept, setConcept] = useState(initialConcept);
  const [view, setView] = useState(() => initialView(location.search));
  const [category, setCategory] = useState('all');
  const [query, setQuery] = useState('');
  const [sort, setSort] = useState('default');
  const [favorites, setFavorites] = useState(() => { const value = saved('koko-design-favorites', []); return Array.isArray(value) ? value.filter(id => products.some(p => p.id === id)) : []; });
  const [cart, setCart] = useState(initialCart);
  const [chosen, setChosen] = useState(() => { const value = saved('koko-design-choice', null); return concepts.some(c => c.id === value) ? value : null; });
  const [overlay, setOverlay] = useState(null);
  const [toast, setToast] = useState('');
  const [menu, setMenu] = useState(false);
  const dialog = useRef(null);
  const selection = concepts.find(c => c.id === concept);
  const totalCount = Object.values(cart).reduce((sum, q) => sum + q, 0);
  const list = filterProducts(view === 'favorites' ? products.filter(p => favorites.includes(p.id)) : products, query, category).sort((a, b) => sort === 'low' ? a.price - b.price : sort === 'high' ? b.price - a.price : 0);

  useEffect(() => { try { localStorage.setItem('koko-design-cart', JSON.stringify(cart)); } catch {} }, [cart]);
  useEffect(() => { try { localStorage.setItem('koko-design-favorites', JSON.stringify(favorites)); } catch {} }, [favorites]);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 3600); return () => clearTimeout(timer); }, [toast]);
  useEffect(() => { if (overlay && !dialog.current.open) dialog.current.showModal(); if (!overlay && dialog.current.open) dialog.current.close(); }, [overlay]);
  useEffect(() => { const back = () => { setConcept(initialConcept()); setView(initialView(location.search)); setCategory('all'); setQuery(''); setOverlay(null); }; addEventListener('popstate', back); return () => removeEventListener('popstate', back); }, []);
  function updateUrl(nextConcept, nextView) { const url = new URL(location.href); url.hash = ''; url.searchParams.set('concept', nextConcept); if (nextView !== 'home') url.searchParams.set('view', nextView); else url.searchParams.delete('view'); history.pushState(null, '', url); }
  function switchConcept(id) { setConcept(id); setView('home'); setCategory('all'); setQuery(''); setOverlay(null); setMenu(false); updateUrl(id, 'home'); scrollTo({ top: 0, behavior: 'instant' }); }
  function browse(next = 'all', search = '') { setCategory(next); setQuery(search); setView('catalog'); setMenu(false); setOverlay(null); updateUrl(concept, 'catalog'); scrollTo({ top: 0, behavior: 'instant' }); }
  function home() { setView('home'); setQuery(''); setCategory('all'); setMenu(false); updateUrl(concept, 'home'); scrollTo({ top: 0, behavior: 'instant' }); }
  function showIngredients() { home(); requestAnimationFrame(() => document.getElementById('ingredient-archive')?.scrollIntoView({ block: 'start', behavior: 'instant' })); }
  function add(id) { setCart(current => ({ ...current, [id]: Math.min(20, (current[id] || 0) + 1) })); setToast(`${products.find(p => p.id === id).brand} — в тестовой корзине`); }
  function changeQuantity(id, delta) { setCart(current => { const next = { ...current }; const quantity = Math.max(0, Math.min(20, (next[id] || 0) + delta)); if (quantity) next[id] = quantity; else delete next[id]; return next; }); }
  function toggleFavorite(id) { setFavorites(current => current.includes(id) ? current.filter(value => value !== id) : [...current, id]); }
  function choose() { setChosen(concept); try { localStorage.setItem('koko-design-choice', JSON.stringify(concept)); } catch {} setToast(`Выбран ${selection.title}. Выбор сохранён в этом браузере.`); }
  function showFavorites() { setView('favorites'); setCategory('all'); setQuery(''); setOverlay(null); setMenu(false); updateUrl(concept, 'favorites'); scrollTo({ top: 0, behavior: 'instant' }); }
  function showProfile() { setView('profile'); setOverlay(null); setMenu(false); updateUrl(concept, 'profile'); scrollTo({ top: 0, behavior: 'instant' }); }
  function showPromotions() { home(); requestAnimationFrame(() => document.getElementById('promotions')?.scrollIntoView({ block: 'start', behavior: 'instant' })); }

  return <div className={mobileUI ? 'mobile-ui' : 'desktop-ui'}>
    <a href="#shop-content" className="skip-link">Перейти к содержимому</a>
    <div className="ui-mode-bar"><span>Версия сайта</span><div className="ui-mode-options" role="group" aria-label="Версия сайта">{[['mobile', 'Мобильная'], ['desktop', 'Компьютерная'], ['auto', 'Авто']].map(([mode, label]) => <button key={mode} type="button" aria-pressed={uiMode === mode} onClick={() => switchUI(mode)}>{label}</button>)}</div></div>
    <div className="design-toolbar"><div className="lab-brand"><span>KOKO<span className="lab-dot">.</span></span><small>DESIGN LAB</small></div><SmoothTab items={concepts} selected={concept} onChange={switchConcept} /><button className={`choose-design ${chosen === concept ? 'chosen' : ''}`} onClick={choose}>{chosen === concept ? <><Check size={16} aria-hidden="true" />Выбран</> : 'Выбрать дизайн'}</button><span className="test-label">Тестовая витрина</span></div>
    <div className={`storefront ${concept}`} id={`panel-${concept}`} role="tabpanel" aria-labelledby={`tab-${concept}`}>
      <div className="announcement"><span>{concept === 'electric' ? 'ТВОЯ НОВАЯ BEAUTY-РУТИНА НАЧИНАЕТСЯ ЗДЕСЬ' : concept === 'gloss' ? 'Красота в каждом маленьком ритуале' : 'Уход, в котором всё на своём месте'}</span><button onClick={() => setOverlay({ type: 'info', title: 'Тестовый магазин', text: 'Это дизайн-концепт KOKO. Ассортимент и цены демонстрационные. Заказ и оплата доступны только на основном сайте после подключения магазина.' })}>Ассортимент и цены — демо</button></div>
      {mobileUI && <MobileHeader home={home} browse={browse} query={query} setQuery={setQuery} showProfile={showProfile} />}
      <header className="shop-header"><div className="header-main"><BrandLogo onClick={home} /><button className="catalog-button" onClick={() => browse()}><Menu size={20} aria-hidden="true" /><span>Каталог</span></button><form className="search-form" onSubmit={event => { event.preventDefault(); browse('all', query); }}><Search size={20} aria-hidden="true" /><input type="search" aria-label="Найти косметику или бренд" placeholder="Найти свой уход или любимый бренд" value={query} onChange={e => setQuery(e.target.value)} /><button type="submit" aria-label="Искать"><ChevronRight size={18} aria-hidden="true" /></button></form><div className="header-actions"><IconButton label="Магазины KOKO" onClick={() => setOverlay({ type: 'info', title: 'Магазины KOKO', text: 'Адреса магазинов, контакты и доступный ассортимент можно посмотреть на основном сайте KOKO.' })}><MapPin size={21} aria-hidden="true" /></IconButton><IconButton label="Личный кабинет" onClick={showProfile}><UserRound size={21} aria-hidden="true" /></IconButton><IconButton label={`Избранное: ${favorites.length}`} onClick={showFavorites}><Heart size={21} aria-hidden="true" />{favorites.length > 0 && <span className="counter">{favorites.length}</span>}</IconButton><IconButton label={`Корзина: ${totalCount}`} onClick={() => setOverlay({ type: 'cart' })}><ShoppingBag size={22} aria-hidden="true" /><span className="counter">{totalCount}</span></IconButton><IconButton label={menu ? 'Закрыть меню' : 'Открыть меню'} className="mobile-menu-button" onClick={() => setMenu(!menu)} aria-expanded={menu}>{menu ? <X aria-hidden="true" /> : <Menu aria-hidden="true" />}</IconButton></div></div>
        <nav className={`shop-nav ${menu ? 'menu-open' : ''}`} aria-label="Категории магазина"><button onClick={() => browse()}>Вся косметика</button><button onClick={() => browse('cleansing')}>Очищение</button><button onClick={() => browse('toner')}>Тонеры</button><button onClick={() => browse('serum')}>Сыворотки</button><button onClick={() => browse('cream')}>Кремы</button><button onClick={() => browse('spf')}>SPF</button><details className="brand-menu"><summary>Бренды<ChevronDown size={14} aria-hidden="true" /></summary><div>{products.map(p => <button key={p.id} onClick={event => { browse('all', p.brand); event.currentTarget.closest('details').open = false; }}>{p.brand}</button>)}</div></details><button className="nav-promotions" onClick={showPromotions}>Промо</button><button className="nav-editor-pick" onClick={() => concept === 'skin' ? showIngredients() : browse('all', 'ANUA')}>{concept === 'gloss' ? 'Выбор редакции' : concept === 'skin' ? 'По составу' : 'K-beauty edit'}</button></nav>
      </header>
      <main id="shop-content">
        {view === 'profile' ? <Profile favorites={favorites} cart={cart} browse={browse} open={p => setOverlay({ type: 'product', product: p })} toggleFavorite={toggleFavorite} openCart={() => setOverlay({ type: 'cart' })} home={home} notify={setToast} /> : view === 'home' && mobileUI ? <MobileHome concept={concept} browse={browse} showProfile={showProfile} renderProduct={p => <ProductCard key={p.id} product={p} favorite={favorites.includes(p.id)} quantity={cart[p.id] || 0} toggleFavorite={toggleFavorite} add={add} open={p => setOverlay({ type: 'product', product: p })} />} /> : view === 'home' ? <>
          {concept === 'maison' ? <MaisonHero browse={browse} /> : concept === 'electric' ? <ElectricHero browse={browse} open={p => setOverlay({ type: 'product', product: p })} /> : concept === 'gloss' ? <GlossHero browse={browse} open={p => setOverlay({ type: 'product', product: p })} /> : <SkinHero browse={browse} open={p => setOverlay({ type: 'product', product: p })} />}
          <div className="category-discovery section-wrap"><span>{concept === 'skin' ? 'С чего начнём?' : 'Твоя beauty-полка'}</span>{categories.slice(1).map((c, index) => <button key={c.id} onClick={() => browse(c.id)}><span>{c.name}</span><span className={`category-visual category-${c.id}`}><ProductImage product={products[[0, 1, 2, 4, 3][index]]} /></span></button>)}</div>
          <section className="product-section section-wrap" id="product-shelf"><div className="section-heading"><h2>{concept === 'electric' ? 'На твою полку' : concept === 'gloss' ? 'В вашей новой косметичке' : 'База, с которой легко начать'}</h2><button className="text-button" onClick={() => browse()}>Весь каталог</button></div><div className="product-grid">{products.slice(0, 4).map(p => <ProductCard key={p.id} product={p} favorite={favorites.includes(p.id)} quantity={cart[p.id] || 0} toggleFavorite={toggleFavorite} add={add} open={p => setOverlay({ type: 'product', product: p })} />)}</div><p className="price-disclosure">Тестовый ассортимент и демонстрационные цены.</p></section>
          <Promotions concept={concept} browse={browse} open={p => setOverlay({ type: 'product', product: p })} notify={setToast} showProfile={showProfile} />
          <EditorialSections concept={concept} browse={browse} open={p => setOverlay({ type: 'product', product: p })} />
          <section className="social-section section-wrap"><div><Instagram size={22} aria-hidden="true" /><h2>KOKO в твоей ленте</h2><p>Новые текстуры, находки и уход в реальной жизни.</p><a href="https://koko.kz/" target="_blank" rel="noopener noreferrer">Соцсети на сайте KOKO</a></div><img src="./images/koko-social.jpg" alt="Подборка косметики из материалов KOKO" loading="lazy" /><div className="social-type">beauty<br />in real<br /><i>life.</i></div></section>
        </> : <section className="catalog-page section-wrap"><div className="catalog-top"><button className="text-button" onClick={home}>Главная</button><span>/ {view === 'favorites' ? 'Избранное' : 'Каталог'}</span></div><div className="section-heading"><div><h1>{view === 'favorites' ? 'Твоё избранное' : 'Косметика KOKO'}</h1><p>{view === 'favorites' ? 'Любимые находки — в одном месте.' : 'Выбери свой следующий шаг в уходе.'}</p></div><label className="sort-control"><SlidersHorizontal size={17} aria-hidden="true" /><select aria-label="Сортировка товаров" value={sort} onChange={e => setSort(e.target.value)}><option value="default">Наш выбор</option><option value="low">Сначала дешевле</option><option value="high">Сначала дороже</option></select></label></div><div className="catalog-filters" aria-label="Фильтр категорий">{categories.map(c => <button key={c.id} className={category === c.id ? 'active' : ''} aria-pressed={category === c.id} onClick={() => setCategory(c.id)}>{c.name}</button>)}</div>{query && <div className="search-status">По запросу «{query}»<button onClick={() => setQuery('')} aria-label="Очистить поиск"><X size={18} aria-hidden="true" /></button></div>}<p className="catalog-count" aria-live="polite">Найдено товаров: {list.length}</p>{list.length ? <div className="product-grid">{list.map(p => <ProductCard key={p.id} product={p} favorite={favorites.includes(p.id)} quantity={cart[p.id] || 0} toggleFavorite={toggleFavorite} add={add} open={p => setOverlay({ type: 'product', product: p })} />)}</div> : <div className="empty-state"><Heart size={34} aria-hidden="true" /><h2>{view === 'favorites' ? 'Здесь будут ваши находки' : 'Ничего не нашлось'}</h2><p>{view === 'favorites' ? 'Нажмите на сердце в карточке товара.' : 'Попробуйте другой бренд или сбросьте фильтры.'}</p><button className="primary-button" onClick={() => browse()}>Смотреть все товары</button></div>}<p className="price-disclosure">Тестовый ассортимент и демонстрационные цены.</p></section>}
      </main>
      {mobileUI && <MobileDock view={view} cartOpen={overlay?.type === 'cart'} home={home} browse={browse} showFavorites={showFavorites} showProfile={showProfile} openCart={() => setOverlay({ type: 'cart' })} totalCount={totalCount} favoriteCount={favorites.length} />}
      <SiteFooter mobileUI={mobileUI} home={home} browse={browse} showFavorites={showFavorites} showProfile={showProfile} showPromotions={showPromotions} showInfo={setOverlay} />
      <dialog ref={dialog} className={`shop-dialog ${overlay?.type === 'cart' ? 'cart-dialog' : ''}`} onCancel={() => setOverlay(null)} onClick={e => { if (e.target === dialog.current) { const rect = dialog.current.getBoundingClientRect(); if (e.clientX < rect.left || e.clientX > rect.right || e.clientY < rect.top || e.clientY > rect.bottom) setOverlay(null); } }} aria-label={overlay?.type === 'cart' ? 'Тестовая корзина' : overlay?.type === 'product' ? overlay.product.name : overlay?.title || 'Информация'}><IconButton label="Закрыть окно" className="dialog-close" onClick={() => setOverlay(null)}><X aria-hidden="true" /></IconButton>
        {overlay?.type === 'product' && <div className="product-detail"><div className="detail-image" style={{ background: overlay.product.color }}><ProductImage product={overlay.product} loading="eager" /></div><div className="detail-content"><span className="product-brand">{overlay.product.brand}</span><h2>{overlay.product.name}</h2><p>{overlay.product.type} · {overlay.product.volume}</p><b className="detail-price">{money(overlay.product.price)}</b><p className="detail-description">{overlay.product.description}</p><button className="primary-button" disabled={(cart[overlay.product.id] || 0) >= 20} onClick={() => add(overlay.product.id)}><ShoppingBag size={19} aria-hidden="true" />{cart[overlay.product.id] ? `В корзине: ${cart[overlay.product.id]} · добавить` : 'В тестовую корзину'}</button><button className="text-button" onClick={() => toggleFavorite(overlay.product.id)}><Heart size={18} fill={favorites.includes(overlay.product.id) ? 'currentColor' : 'none'} aria-hidden="true" />{favorites.includes(overlay.product.id) ? 'В избранном' : 'Сохранить в избранное'}</button><small>Демонстрационная цена. Прототип не принимает заказы.</small></div></div>}
        {overlay?.type === 'cart' && <div className="cart-content"><h2>Твоя корзина<span>{totalCount}</span></h2><p className="cart-demo-note">Тестовая корзина · без оформления заказа</p>{totalCount ? <><div className="cart-lines">{products.filter(p => cart[p.id]).map(p => <div className="cart-line" key={p.id}><ProductImage product={p} /><div><span>{p.brand}</span><h3>{p.name}</h3><b>{money(p.price)}</b><div className="quantity-control"><button onClick={() => changeQuantity(p.id, -1)} aria-label={`Уменьшить количество ${p.name}`}><Minus size={15} aria-hidden="true" /></button><span>{cart[p.id]}</span><button onClick={() => changeQuantity(p.id, 1)} disabled={cart[p.id] >= 20} aria-label={`Увеличить количество ${p.name}`}><Plus size={15} aria-hidden="true" /></button><button className="remove-item" onClick={() => setCart(current => { const next = { ...current }; delete next[p.id]; return next; })} aria-label={`Удалить ${p.name}`}><X size={17} aria-hidden="true" /></button></div></div></div>)}</div><div className="cart-summary"><span>Итого</span><b>{money(basketTotal(cart))}</b></div><button className="primary-button" onClick={() => setOverlay(null)}>Продолжить выбор</button><p className="cart-demo-note">Товары сохраняются только в этом браузере. Для покупок откройте основной сайт KOKO.</p></> : <div className="empty-state"><ShoppingBag size={38} aria-hidden="true" /><h3>Пока здесь пусто</h3><p>Добавьте понравившийся уход.</p><button className="primary-button" onClick={() => browse()}>В каталог</button></div>}</div>}
        {overlay?.type === 'info' && <div className="info-dialog"><h2>{overlay.title}</h2><p>{overlay.text}</p><a className="primary-button" href={liveSite} target="_blank" rel="noopener noreferrer">Основной сайт KOKO</a></div>}
      </dialog>
    </div>
    {toast && <div className="toast" role="status"><Check size={18} aria-hidden="true" /><span>{toast}</span><button aria-label="Закрыть уведомление" onClick={() => setToast('')}><X size={16} aria-hidden="true" /></button></div>}
  </div>;
}
